### ISSUE TITLE
Failed to create new file 

### ISSUE THREAD

**Issue by carsonwang** [zjf2012/daos#10]
When running TeraSort, got the following error.

Failed to find parent directory (/HiBench/Terasort/Output/_temporary/0/_temporary/attempt_20191218153837_0006_r_000004_0) error code: 2 error msg: No such file or directory
        at com.intel.daos.client.DaosFsClient.createNewFile(Native Method)
        at com.intel.daos.client.DaosFile.createNewFile(DaosFile.java:140)
        at com.intel.daos.hadoop.fs.DaosFileSystem.create(DaosFileSystem.java:140)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:911)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:892)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:789)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:778)

**Comment by zjf2012** [comment]
It's fixed by forcing creating new file when DaosFileSystem.create(). "Forcing" means to create new file's parent directory if it doesn't exist.
