### ISSUE TITLE
Failed to run with Spark on Yarn

### ISSUE THREAD

**Issue by carsonwang** [zjf2012/daos#12]
Seems to be a problem when uploading the files to DAOS. This may be related to #10. We can review this later. 

19/12/18 15:53:40 main INFO Client: Uploading resource file:/mnt/DP_disk4/yuzhou/spark/spark-37c19494-41ad-4c4d-9560-a8ad628dfc75/__spark_libs__4591026259216981698.zip -> daos://null/user/yuzhou/.sparkStaging/application_1573004767711_0024/__spark_libs__4591026259216981698.zip
19/12/18 15:53:40 main INFO Client: Deleted staging directory daos://null/user/yuzhou/.sparkStaging/application_1573004767711_0024
19/12/18 15:53:40 main ERROR SparkContext: Error initializing SparkContext.
org.apache.hadoop.fs.UnsupportedFileSystemException: fs.AbstractFileSystem.daos.impl=null: No AbstractFileSystem configured for scheme: daos
        at org.apache.hadoop.fs.AbstractFileSystem.createFileSystem(AbstractFileSystem.java:160)
        at org.apache.hadoop.fs.AbstractFileSystem.get(AbstractFileSystem.java:249)
        at org.apache.hadoop.fs.FileContext$2.run(FileContext.java:334)
        at org.apache.hadoop.fs.FileContext$2.run(FileContext.java:331)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.fs.FileContext.getAbstractFileSystem(FileContext.java:331)
        at org.apache.hadoop.fs.FileContext.getFileContext(FileContext.java:448)
        at org.apache.spark.deploy.yarn.Client$$anonfun$10.apply(Client.scala:395)
        at org.apache.spark.deploy.yarn.Client$$anonfun$10.apply(Client.scala:394)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
        at org.apache.spark.deploy.yarn.Client.copyFileToRemote(Client.scala:394)
        at org.apache.spark.deploy.yarn.Client.org$apache$spark$deploy$yarn$Client$$distribute$1(Client.scala:476)
        at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:563)
        at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:864)
        at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:178)

**Comment by zjf2012** [comment]
From the msg,
 "org.apache.hadoop.fs.UnsupportedFileSystemException: fs.AbstractFileSystem.daos.impl=null: No AbstractFileSystem configured for scheme: daos", 
we can see our DaosFileSystem didn't get registered as service impl of Hadoop FS. 

In latest build, we put registering into jar. This issue should be fixed.

**Comment by zjf2012** [comment]
Check this email for how registering DaosFileSystem with schema of 'daos' inside self-included jar.

[HDFS Impl Configuration.zip](https://github.com/zjf2012/daos/files/4018183/HDFS.Impl.Configuration.zip)
