### ISSUE TITLE
Failed to open file (/HiBench/Terasort/Input2/part-m-00052) with flags (2) error code: 22 error msg: Invalid argument

### ISSUE THREAD

**Issue by minmingzhu** [zjf2012/daos#20]
Tested by  tearsort spark  found  . In the time running of tearsort , the tearsort can run normally when one executor  has one core  or multiple executors but only one core per executor  , but an exception occurs when one executor has multiple cores .  This test just uses daos as input and output, there is no remoteshuffle process . 
When one executor has multiple cores , it would has following error information . 
```
Failed to open file (/HiBench/Terasort/Input2/part-m-00052) with flags (2) error code: 22 error msg: Invalid argument
	at com.intel.daos.client.DaosFsClient.dfsLookup(Native Method)
	at com.intel.daos.client.DaosFile.open(DaosFile.java:178)
	at com.intel.daos.client.DaosFile.exists(DaosFile.java:439)
	at com.intel.daos.hadoop.fs.DaosFileSystem.open(DaosFileSystem.java:158)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:769)
	at org.apache.hadoop.examples.terasort.TeraInputFormat$TeraRecordReader.initialize(TeraInputFormat.java:226)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.liftedTree1$1(NewHadoopRDD.scala:199)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:196)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:151)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:70)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.PartitionPruningRDD.compute(PartitionPruningRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)	
```
but multiple executors when running tpch, each executor can execute normally when there are multiple cores .

**Comment by zjf2012** [comment]
@minmingzhu fixed by adding reference count to DaosFsClient so that disconnect method doesn't actually unload DFS if there are still other reference to it.
