### ISSUE TITLE
Failed to find parent directory or create parent directory (/dbgen/output/Q09/_temporary/0/_temporary/attempt_20191224172845_0024_m_000118_0) error code: 2 error msg: No such file or directory

### ISSUE THREAD

**Issue by minmingzhu** [zjf2012/daos#22]
When per of executor has multiple cores , it would happen this error : 

```
Failed to find parent directory or create parent directory (/dbgen/output/Q09/_temporary/0/_temporary/attempt_20191224172845_0024_m_000118_0) error code: 2 error msg: No such file or directory
	at com.intel.daos.client.DaosFsClient.createNewFile(Native Method)
	at com.intel.daos.client.DaosFile.createNewFile(DaosFile.java:158)
	at com.intel.daos.hadoop.fs.DaosFileSystem.create(DaosFileSystem.java:187)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:911)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:892)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:789)
	at org.apache.spark.sql.execution.datasources.CodecStreams$.createOutputStream(CodecStreams.scala:81)
	at org.apache.spark.sql.execution.datasources.CodecStreams$.createOutputStreamWriter(CodecStreams.scala:92)
	at org.apache.spark.sql.execution.datasources.csv.CsvOutputWriter.<init>(CSVFileFormat.scala:177)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat$$anon$1.newInstance(CSVFileFormat.scala:85)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.newOutputWriter(FileFormatDataWriter.scala:120)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.<init>(FileFormatDataWriter.scala:108)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:233)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:169)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:168)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zjf2012** [comment]
@minmingzhu , as confirmed by daos, Zhen Liang, it'll be fixed by the new feature, 'conditional update'. For now, we mitigate the issue by retrying lookup up to 100 times.

**Comment by zjf2012** [comment]
not our issue
