### ISSUE TITLE
Add fs.daos.pool.svc configuration tag in daos-site-example.xml

### ISSUE THREAD

**Issue by gczsjdy** [zjf2012/daos#34]
I have encountered
```
20/02/06 23:00:48 ERROR Executor: Exception in task 4.0 in stage 1.0 (TID 104)
java.lang.IllegalArgumentException: fs.daos.pool.svc is null, need to set up fs.daos.pool.svc in hdfs.xml .
        at com.intel.daos.hadoop.fs.DaosFileSystem.initialize(DaosFileSystem.java:217)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
```
And I added it myself to resolve.

**Comment by gczsjdy** [comment]
Resolved
